name: Docker Image

on:
  push:
    branches: [main, master]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - id: meta
        run: echo "version=$(node -p \"require('./resenas-libros/package.json').version\")" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./resenas-libros
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/resenas-libros:latest
            ghcr.io/${{ github.repository }}/resenas-libros:${{ steps.meta.outputs.version }}
            ghcr.io/${{ github.repository }}/resenas-libros:${{ github.sha }}
